### ISSUE TITLE
Undefined symbol error when calling higher order function

### ISSUE THREAD

**Issue by tesujiro** [mattn/anko#267] opened 2018-07-22 02:12 UTC
Some kind of higher order function occurs undefined symbol error.
No error in the code below.
```
> func(x){return func(){return x}}(1)()
1
```
But 
```
> func(x){if true {return func(){return x}}}(1)()
1:32 undefined symbol 'x'
```

**Comment by MichaelS11** [comment] 2018-07-23 04:42
In this particular case, this is caused by the `newenv.Destroy()` on this line:
https://github.com/mattn/anko/blob/master/vm/vmStmt.go#L153

Maybe the solution is to remove all the Destroy calls from vm code?

@mattn 
Any thoughts?

**Comment by mattn** [comment] 2018-07-23 04:51
Yes, when the reference goes out of scope, it will be removed by GC.

**Closed** 2018-07-24 00:36 UTC
